// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHAdutghIDOECnpNlt5IlRQacNVXD_ElU',
    appId: '1:358609484742:web:31b035544ad62a116490c7',
    messagingSenderId: '358609484742',
    projectId: 'flutter-project-01-c13db',
    authDomain: 'flutter-project-01-c13db.firebaseapp.com',
    storageBucket: 'flutter-project-01-c13db.appspot.com',
    measurementId: 'G-9TL34BQ424',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiIvpDu13rssT2C3h9icJ39p8IzFJao9Q',
    appId: '1:358609484742:android:38798db152bea4eb6490c7',
    messagingSenderId: '358609484742',
    projectId: 'flutter-project-01-c13db',
    storageBucket: 'flutter-project-01-c13db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumkFciPSWvENAZRKaU07zGr0VKNn1lr8',
    appId: '1:358609484742:ios:5f0180235d02c9146490c7',
    messagingSenderId: '358609484742',
    projectId: 'flutter-project-01-c13db',
    storageBucket: 'flutter-project-01-c13db.appspot.com',
    iosBundleId: 'com.example.mynewproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumkFciPSWvENAZRKaU07zGr0VKNn1lr8',
    appId: '1:358609484742:ios:b17e0ab60dbf7a276490c7',
    messagingSenderId: '358609484742',
    projectId: 'flutter-project-01-c13db',
    storageBucket: 'flutter-project-01-c13db.appspot.com',
    iosBundleId: 'com.example.mynewproject.RunnerTests',
  );
}
